### ISSUE TITLE
Can't enable "LANGCHAIN_TRACING_V2" to do tracing in Hierarchical Agent Teams example

### ISSUE THREAD

**Issue by timeff** [langchain-ai/langgraphjs#514]
Hi, I am building the application using a hierarchical agent team. But when I enable the "LANGCHAIN_TRACING_V2" environment variable to send the data to the langsmith. I got the error

```
Error: Key team_members not found in channels
    at validateKeys (/Users/xxx/Lab/langchain-hierarchy-supervisor/node_modules/@langchain/langgraph/dist/pregel/validate.cjs:84:23)
    at CompiledStateGraph._defaults (/Users/xxx/Lab/langchain-hierarchy-supervisor/node_modules/@langchain/langgraph/dist/pregel/index.cjs:400:44)
    at CompiledStateGraph._streamIterator (/Users/xxx/Lab/langchain-hierarchy-supervisor/node_modules/@langchain/langgraph/dist/pregel/index.cjs:517:112)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  pregelTaskId: '2aa7cc38-a59e-5593-8b06-2b6963bc24fd'
```

At first, I thought it might be a problem with my application. But I created a new project and try copy and paste anything from the official tutorial at https://langchain-ai.github.io/langgraphjs/tutorials/multi_agent/hierarchical_agent_teams/. It turned out the same error happened again.

I can disable tracing by putting the environment variable to false but it will lose all of the tracing capability using langsmith.

**Comment by lemonps** [comment]
I have the same problem. Anyone know the solution?

**Comment by jacoblee93** [comment]
Very weird - will investigate!

**Comment by rpatel15-hue** [comment]
same issue for me

**Comment by Pdash-exceeds** [comment]
Same issue, works for subgraphs. Not for supergraph

**Comment by jacoblee93** [comment]
Hey all, sorry for the delay - will look into it

**Comment by phpmac** [comment]
hello

**Comment by dqbd** [comment]
Hello! We're in the process of rewriting our examples, closing this issue for staleness
